### ISSUE TITLE
Will this work for cm-14.1?

### ISSUE THREAD

**Issue by dimitry-ishenko** [GloriamSemper/android_device_amazon_mustang#1]
Trying to sync and build cm-14.1 branch of LOS, but figured I'd ask, while I wait :smile:

**Comment by R0rt1z2** [comment]
Did you mind looking at ggow sources?
https://github.com/ggow/android_device_amazon_mustang

**Comment by dimitry-ishenko** [comment]
@R0rt1z2 I have. Was able to compile with some tweaks, but seeing major issues with video. My (uneducated) guess is it's something to do with OpenGL.

He's not replying on the xda forums. I guess I can try pinging him on github.

Let me know if you have any other ideas. Otherwise, feel free to  close this issue. Thanks for replying.

**Comment by R0rt1z2** [comment]
> @R0rt1z2 I have. Was able to compile with some tweaks, but seeing major issues with video. My (uneducated) guess is it's something to do with OpenGL.
> 
> He's not replying on the xda forums. I guess I can try pinging him on github.
> 
> Let me know if you have any other ideas. Otherwise, feel free to close this issue. Thanks for replying.

Hi,

No problem. He doesn't reply because it's having some personal stuff atm and it's giving itself a break. Pinging him in github will do nothing xD

About the video, you should attach some logcats to see what's wrong there.

Regards.

**Comment by GloriamSemper** [comment]
Hi, sorry for delayed response. Been super busy with work. This is a side hobby for me when I get the time.

These repos for Mustang is based on Lineage 16.0 Karnak repos because the Karnak model also uses the MediaTek MT8163 SoC and has similar amount of RAM. I've been tweaking it for Mustang and am only having issues building the kernel at this time. I'll open up an issue with some logs when I can if anyone would like to help me figure out what's going wrong.

**Comment by R0rt1z2** [comment]
> Hi, sorry for delayed response. Been super busy with work. This is a side hobby for me when I get the time.
> 
> These repos for Mustang is based on Lineage 16.0 Karnak repos because the Karnak model also uses the MediaTek MT8163 SoC and has similar amount of RAM. I've been tweaking it for Mustang and am only having issues building the kernel at this time. I'll open up an issue with some logs when I can if anyone would like to help me figure out what's going wrong.

I see that you're using karnak's kernel source to build the kernel...

Maybe you should only cherry-pick the required changes by Android 9.0 to the mustang's kernel source.

Regards.
